#!/bin/sh

# basic env checks
[ -z "$CALLER" ] && echo "Specify CALLER env variable to detect script ID" && exit 1

[ -z "$(type -p python)" ] && echo "[ $CALLER ] 'python' is required (type -p python)" && exit 1
[ -z "$(type -p pyenv)" ] && echo "[ $CALLER ] 'pyenv' is not installed (type -p pyenv)" && exit 1
[ -z "$(type -p node)" ] && echo "[ $CALLER ] 'node' is not installed (type -p node)" && exit 1
[ -z "$(type -p npm)" ] && echo "[ $CALLER ] 'npm' is not installed (type -p npm)" && exit 1


# system functions
function abort() {
    echo "[ ${CALLER} ] ABORT: $1" >&2;
    exit 1
}

function log() {
    echo "[ $CALLER ] $1" >&2;
}

function help() {
    if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
      echo "[ $CALLER ] Help:" >&2;
      printf "%s" "$2" >&2;
      echo
      echo
      exit 1
    fi
}
